// Generated by gencpp from file kaka_interface_pkg/InterfaceCtrl.msg
// DO NOT EDIT!


#ifndef KAKA_INTERFACE_PKG_MESSAGE_INTERFACECTRL_H
#define KAKA_INTERFACE_PKG_MESSAGE_INTERFACECTRL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kaka_interface_pkg
{
template <class ContainerAllocator>
struct InterfaceCtrl_
{
  typedef InterfaceCtrl_<ContainerAllocator> Type;

  InterfaceCtrl_()
    : Cmd(0)  {
    }
  InterfaceCtrl_(const ContainerAllocator& _alloc)
    : Cmd(0)  {
  (void)_alloc;
    }



   typedef int32_t _Cmd_type;
  _Cmd_type Cmd;




  typedef boost::shared_ptr< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> const> ConstPtr;

}; // struct InterfaceCtrl_

typedef ::kaka_interface_pkg::InterfaceCtrl_<std::allocator<void> > InterfaceCtrl;

typedef boost::shared_ptr< ::kaka_interface_pkg::InterfaceCtrl > InterfaceCtrlPtr;
typedef boost::shared_ptr< ::kaka_interface_pkg::InterfaceCtrl const> InterfaceCtrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kaka_interface_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'kaka_interface_pkg': ['/home/leo/Desktop/Kaka_Project/src/kaka_interface_pkg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "269bcf4b8e9f4499f088fe6b4f64bdda";
  }

  static const char* value(const ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x269bcf4b8e9f4499ULL;
  static const uint64_t static_value2 = 0xf088fe6b4f64bddaULL;
};

template<class ContainerAllocator>
struct DataType< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kaka_interface_pkg/InterfaceCtrl";
  }

  static const char* value(const ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 Cmd\n\
";
  }

  static const char* value(const ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InterfaceCtrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kaka_interface_pkg::InterfaceCtrl_<ContainerAllocator>& v)
  {
    s << indent << "Cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KAKA_INTERFACE_PKG_MESSAGE_INTERFACECTRL_H
