controller_list:
  - name: fake_gripper_controller
    joints:
      - finger_joint1
      - finger_joint2
  - name: fake_arm_controller
    joints:
      - shoulder_roll_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - gripper_roll_joint